"""
test_e2e.py – End-to-End integration test for OSInt Location Monitor
Version: 0.6.0 | 2026-03-10

Tests the full pipeline:
  1. Supabase: read locations, write synthetic alert, read it back, clean up
  2. Monitor: dry-run all 5 checkers against a real location (Munich)
  3. Monitor: force-inject a synthetic alert → Telegram message sent
  4. Morning report: dry-run against Munich → Telegram message sent
  5. Summary report

Usage:
  python scripts/test_e2e.py                  # full E2E with real Telegram msgs
  python scripts/test_e2e.py --dry-run        # skip Telegram sends
  python scripts/test_e2e.py --skip-telegram  # alias for --dry-run
  python scripts/test_e2e.py --verbose        # DEBUG-level logging

Exit codes: 0 = all passed, 1 = one or more tests failed
"""

import sys
import os
import json
import argparse
import requests
from datetime import datetime, timezone, timedelta
from typing import Optional

# Ensure scripts/ is in path so utils is importable
sys.path.insert(0, __file__.rsplit("/", 1)[0])

from utils import (
    load_environment, setup_logging, get_required_env,
    send_telegram,
)
from loguru import logger


# ─────────────────────────────────────────────
# Test configuration
# ─────────────────────────────────────────────

# Munich, Germany – reliable data for all checkers
E2E_TEST_LOCATION = {
    "id":   "e2e-test-00000000",  # synthetic, never real UUID
    "name": "[E2E-Test] München",
    "lat":  48.1351,
    "lon":  11.5820,
}

PASS = "✅ PASS"
FAIL = "❌ FAIL"
SKIP = "⏭️  SKIP"
WARN = "⚠️  WARN"

# ─────────────────────────────────────────────
# Result tracker
# ─────────────────────────────────────────────

results: dict[str, str] = {}
details: dict[str, str] = {}


def record(name: str, status: str, detail: str = "") -> None:
    """Record a test result."""
    results[name] = status
    if detail:
        details[name] = detail


# ─────────────────────────────────────────────
# 1. Supabase pipeline test
# ─────────────────────────────────────────────

def test_supabase_pipeline() -> bool:
    """
    Full Supabase round-trip:
      - Connect with service key
      - Read locations table
      - Insert a synthetic test alert
      - Read it back
      - Delete it (cleanup)
    """
    logger.info("── Supabase Pipeline ──────────────────────────")
    try:
        from supabase import create_client
        url = get_required_env("SUPABASE_URL")
        key = get_required_env("SUPABASE_SERVICE_KEY")
        sb  = create_client(url, key)

        # a) Read locations
        resp = sb.table("locations").select("id, name, lat, lon").execute()
        locations = resp.data or []
        logger.info(f"Locations in DB: {len(locations)}")
        for loc in locations[:5]:  # show first 5
            logger.info(f"  • {loc.get('name')} ({loc.get('lat')}, {loc.get('lon')})")

        # b) Insert synthetic alert
        test_alert = {
            "location_id":    None,   # no FK for test alert
            "category":       "unwetter",
            "severity":       "test",
            "title":          "[E2E TEST] Synthetic alert – bitte ignorieren",
            "description":    "Auto-generated by test_e2e.py – will be deleted immediately",
            "source_url":     "https://github.com/cryptoclemens/osint-location-monitor",
            "telegram_sent":  False,
            "raw_data":       {"e2e": True, "ts": datetime.now(timezone.utc).isoformat()},
        }
        insert_resp = sb.table("alerts").insert(test_alert).execute()
        inserted_id = insert_resp.data[0]["id"] if insert_resp.data else None

        if not inserted_id:
            record("SUPABASE_WRITE", FAIL, "Insert returned no ID")
            return False

        logger.success(f"Synthetic alert inserted – id={inserted_id}")

        # c) Read it back
        read_resp = sb.table("alerts").select("id, title").eq("id", inserted_id).execute()
        if not read_resp.data:
            record("SUPABASE_READ", FAIL, "Could not read back inserted alert")
            return False
        logger.success(f"Alert read-back OK: '{read_resp.data[0]['title'][:60]}'")

        # d) Cleanup
        sb.table("alerts").delete().eq("id", inserted_id).execute()
        verify = sb.table("alerts").select("id").eq("id", inserted_id).execute()
        if verify.data:
            record("SUPABASE_CLEANUP", WARN, "Deletion may not have worked")
        else:
            logger.success("Test alert deleted – Supabase cleanup OK")

        record("SUPABASE_PIPELINE", PASS,
               f"{len(locations)} location(s) in DB, write/read/delete cycle OK")
        return True

    except Exception as e:
        logger.error(f"Supabase pipeline failed: {e}")
        record("SUPABASE_PIPELINE", FAIL, str(e))
        return False


# ─────────────────────────────────────────────
# 2. Monitor: dry-run all checkers against Munich
# ─────────────────────────────────────────────

def test_monitor_checkers() -> bool:
    """
    Import monitor.py checkers and run them against Munich.
    Does NOT send Telegram messages – just verifies each checker
    returns a valid result (dict alert or None) without crashing.
    """
    logger.info("── Monitor Checkers (dry-run) ─────────────────")
    try:
        # Import checker functions from monitor.py
        import importlib.util, pathlib
        spec = importlib.util.spec_from_file_location(
            "monitor",
            pathlib.Path(__file__).parent / "monitor.py"
        )
        monitor = importlib.util.load_from_spec(spec)
        spec.loader.exec_module(monitor)

        lat = E2E_TEST_LOCATION["lat"]
        lon = E2E_TEST_LOCATION["lon"]
        passed = 0
        failed = 0

        # Weather checker
        try:
            result = monitor.check_weather(lat, lon)
            logger.success(f"check_weather → {'alert triggered' if result else 'no alert (normal)'}")
            record("CHECKER_WEATHER", PASS)
            passed += 1
        except Exception as e:
            logger.error(f"check_weather failed: {e}")
            record("CHECKER_WEATHER", FAIL, str(e))
            failed += 1

        # Earthquake checker
        try:
            result = monitor.check_earthquakes(lat, lon)
            logger.success(f"check_earthquakes → {'alert triggered' if result else 'no alert (normal)'}")
            record("CHECKER_EARTHQUAKES", PASS)
            passed += 1
        except Exception as e:
            logger.error(f"check_earthquakes failed: {e}")
            record("CHECKER_EARTHQUAKES", FAIL, str(e))
            failed += 1

        # GNews checkers (need API key)
        gnews_key = os.getenv("GNEWS_API_KEY")
        if gnews_key:
            for category in ["hochwasser", "feuer", "unruhen"]:
                try:
                    result = monitor.check_gnews(lat, lon, category, gnews_key)
                    logger.success(f"check_gnews({category}) → {'alert triggered' if result else 'no alert (normal)'}")
                    record(f"CHECKER_GNEWS_{category.upper()}", PASS)
                    passed += 1
                except Exception as e:
                    logger.error(f"check_gnews({category}) failed: {e}")
                    record(f"CHECKER_GNEWS_{category.upper()}", FAIL, str(e))
                    failed += 1
        else:
            logger.warning("GNEWS_API_KEY not set – skipping GNews checker tests")
            for cat in ["HOCHWASSER", "FEUER", "UNRUHEN"]:
                record(f"CHECKER_GNEWS_{cat}", SKIP, "No GNEWS_API_KEY")

        summary = f"{passed} passed, {failed} failed"
        record("MONITOR_CHECKERS", PASS if failed == 0 else FAIL, summary)
        logger.info(f"Monitor checkers: {summary}")
        return failed == 0

    except Exception as e:
        logger.error(f"Could not import monitor.py: {e}")
        record("MONITOR_CHECKERS", FAIL, str(e))
        return False


# ─────────────────────────────────────────────
# 3. Synthetic alert → Telegram
# ─────────────────────────────────────────────

def test_synthetic_alert(dry_run: bool = False) -> bool:
    """
    Send a synthetic alert through the Telegram pipeline.
    This mimics what monitor.py does when it detects an event.
    """
    logger.info("── Synthetic Alert → Telegram ─────────────────")
    if dry_run:
        logger.info("DRY-RUN: Telegram send skipped")
        record("SYNTHETIC_ALERT", SKIP, "dry-run mode")
        return True

    try:
        now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        msg = (
            "🧪 *E2E-Test – Synthetischer Alert*\n\n"
            f"📍 *Ort:* {E2E_TEST_LOCATION['name']}\n"
            f"🌩️ *Kategorie:* Unwetter (Test)\n"
            f"⚡ *Schwere:* Simuliert\n\n"
            "Dies ist eine automatisch generierte Test-Nachricht "
            "vom `test_e2e.py`-Script.\n"
            "Sie bestätigt, dass der Alert-Kanal korrekt funktioniert. ✅\n\n"
            f"_Zeitstempel: {now}_"
        )
        send_telegram(msg)
        logger.success("Synthetic alert sent via Telegram ✅")
        record("SYNTHETIC_ALERT", PASS, "Telegram message delivered")
        return True
    except Exception as e:
        logger.error(f"Synthetic alert failed: {e}")
        record("SYNTHETIC_ALERT", FAIL, str(e))
        return False


# ─────────────────────────────────────────────
# 4. Morning report dry-run
# ─────────────────────────────────────────────

def test_morning_report(dry_run: bool = False) -> bool:
    """
    Run morning_report.py against Munich and optionally send via Telegram.
    In dry-run mode: just checks that the report text is generated.
    """
    logger.info("── Morning Report ─────────────────────────────")
    try:
        import importlib.util, pathlib
        spec = importlib.util.spec_from_file_location(
            "morning_report",
            pathlib.Path(__file__).parent / "morning_report.py"
        )
        mr = importlib.util.load_from_spec(spec)
        spec.loader.exec_module(mr)

        lat = E2E_TEST_LOCATION["lat"]
        lon = E2E_TEST_LOCATION["lon"]
        name = E2E_TEST_LOCATION["name"]

        # Fetch weather data (same as morning_report does)
        weather = mr.fetch_weather(lat, lon)
        if not weather:
            record("MORNING_REPORT", FAIL, "fetch_weather returned None")
            return False

        logger.success(f"Weather fetched: {weather.get('temp', '?')}°C, "
                       f"code={weather.get('code', '?')}, "
                       f"wind={weather.get('wind', '?')} km/h")

        # Build the report message
        report_text = mr.build_report(name, weather, recent_alerts=[])
        if not report_text or len(report_text) < 50:
            record("MORNING_REPORT", FAIL, "Report text too short or empty")
            return False

        logger.success(f"Report generated ({len(report_text)} chars)")
        logger.debug(f"Report preview:\n{report_text[:200]}...")

        if dry_run:
            logger.info("DRY-RUN: Telegram send skipped")
            record("MORNING_REPORT", PASS, f"Generated {len(report_text)} chars – Telegram skipped (dry-run)")
        else:
            # Prefix with test indicator
            test_report = f"🧪 *E2E-Test – Morgenbericht*\n\n{report_text}"
            send_telegram(test_report)
            logger.success("Morning report sent via Telegram ✅")
            record("MORNING_REPORT", PASS, f"Generated + sent ({len(report_text)} chars)")

        return True

    except AttributeError as e:
        # morning_report.py might not expose fetch_weather/build_report
        logger.warning(f"morning_report.py API mismatch: {e}")
        logger.info("Falling back to full morning_report run")
        return _test_morning_report_full(dry_run)
    except Exception as e:
        logger.error(f"Morning report test failed: {e}")
        record("MORNING_REPORT", FAIL, str(e))
        return False


def _test_morning_report_full(dry_run: bool) -> bool:
    """Fallback: run morning_report as a subprocess to verify it completes."""
    import subprocess, sys as _sys
    env = os.environ.copy()
    if dry_run:
        env["MORNING_REPORT_DRY_RUN"] = "1"

    result = subprocess.run(
        [_sys.executable, "scripts/morning_report.py"],
        capture_output=True, text=True, env=env, timeout=60
    )
    if result.returncode == 0:
        logger.success("morning_report.py exited 0 ✅")
        record("MORNING_REPORT", PASS, "subprocess exit 0")
        return True
    else:
        logger.error(f"morning_report.py exited {result.returncode}")
        logger.error(result.stderr[-500:] if result.stderr else "(no stderr)")
        record("MORNING_REPORT", FAIL, f"exit {result.returncode}")
        return False


# ─────────────────────────────────────────────
# 5. Vercel health check (if deployed)
# ─────────────────────────────────────────────

def test_vercel_health(base_url: Optional[str] = None) -> bool:
    """
    If VERCEL_URL env var is set, check that the deployed app
    returns HTTP 200 on the login page (all other pages redirect there).
    """
    logger.info("── Vercel Deployment Health ───────────────────")
    url = base_url or os.getenv("VERCEL_URL")
    if not url:
        logger.info("VERCEL_URL not set – skipping deployment health check")
        record("VERCEL_HEALTH", SKIP, "Set VERCEL_URL=https://your-app.vercel.app to enable")
        return True

    # Ensure https prefix
    if not url.startswith("http"):
        url = f"https://{url}"

    try:
        resp = requests.get(f"{url}/login", timeout=15, allow_redirects=True)
        if resp.status_code == 200:
            logger.success(f"Vercel health OK – {url}/login → 200")
            record("VERCEL_HEALTH", PASS, f"HTTP 200 from {url}/login")
            return True
        else:
            logger.warning(f"Unexpected status {resp.status_code} from {url}/login")
            record("VERCEL_HEALTH", WARN, f"HTTP {resp.status_code}")
            return False
    except requests.RequestException as e:
        logger.error(f"Vercel health check failed: {e}")
        record("VERCEL_HEALTH", FAIL, str(e))
        return False


# ─────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────

def print_summary() -> bool:
    """Print results table and return True if all passed/warned."""
    width = 54
    logger.info("")
    logger.info("=" * width)
    logger.info(" E2E TEST RESULTS – OSInt Location Monitor v0.6.0")
    logger.info("=" * width)

    all_ok = True
    for name, status in results.items():
        detail = details.get(name, "")
        line = f"  {status}  {name}"
        if detail:
            line += f"\n          ↳ {detail}"
        logger.info(line)
        if status == FAIL:
            all_ok = False

    logger.info("=" * width)
    if all_ok:
        failed_count = sum(1 for s in results.values() if s == FAIL)
        warn_count   = sum(1 for s in results.values() if s == WARN)
        pass_count   = sum(1 for s in results.values() if s == PASS)
        skip_count   = sum(1 for s in results.values() if s == SKIP)
        logger.success(
            f"DONE  {pass_count} passed · {warn_count} warnings · "
            f"{skip_count} skipped · {failed_count} failed"
        )
    else:
        logger.error("SOME TESTS FAILED – see details above")
    logger.info("=" * width)
    return all_ok


def main() -> int:
    parser = argparse.ArgumentParser(
        description="E2E integration test for OSInt Location Monitor"
    )
    parser.add_argument(
        "--dry-run", "--skip-telegram",
        action="store_true",
        help="Run all tests but skip actual Telegram message sends",
    )
    parser.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Enable DEBUG logging",
    )
    parser.add_argument(
        "--vercel-url",
        metavar="URL",
        help="Vercel deployment URL to health-check (overrides VERCEL_URL env var)",
    )
    args = parser.parse_args()

    load_environment()
    setup_logging("DEBUG" if args.verbose else "INFO")

    logger.info("=" * 54)
    logger.info(" OSInt Location Monitor – E2E Integration Test")
    logger.info(f" Mode: {'DRY-RUN (no Telegram)' if args.dry_run else 'FULL (Telegram enabled)'}")
    logger.info(f" Test location: {E2E_TEST_LOCATION['name']}")
    logger.info("=" * 54)

    # Run all test stages
    test_supabase_pipeline()
    test_monitor_checkers()
    test_synthetic_alert(dry_run=args.dry_run)
    test_morning_report(dry_run=args.dry_run)
    test_vercel_health(base_url=args.vercel_url)

    all_ok = print_summary()
    return 0 if all_ok else 1


if __name__ == "__main__":
    sys.exit(main())
